name:                creatur-dvector-wains
version:             1.1.0
github:              "mhwombat/creatur-dvector-wains"
license:             BSD3
author:              "Amy de Buitléir"
maintainer:          "amy@nualeargais.ie"
copyright:           "2018 Amy de Buitléir"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/creatur-dvector-wains#readme>

dependencies:
- base >= 4.7 && < 5

library:
    source-dirs: src
    ghc-options:
    - -Wall
    - -Werror
    dependencies:
    - cereal
    - containers
    - creatur
    - creatur-wains
    - gray-extended
    - lens
    - MonadRandom
    - mtl
    - som
    - split

tests:
  creatur-dvector-wains-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - creatur-wains
    - creatur-dvector-wains
    - creatur-wains-test-utils
    - numeric-tools
    - QuickCheck
    - test-framework
    - test-framework-quickcheck2
